name: Proactive Change Management

on:
 workflow_dispatch:
    inputs:
      # azure_client_id:
      #   description: 'Azure Client ID'
      #   # required: true
      # azure_client_secret:
      #   description: 'Azure Client Secret'
      #   # required: true
      #   type: string
      # azure_tenant_id:
      #   description: 'Azure Tenant ID'
      #   # required: true
      #   type: string
      # azure_subscription_id:
      #   description: 'Azure Subscription ID'
      #   # required: true
      #   type: string
      servicenow_instance:
        description: 'ServiceNow instance'
        required: true
        type: string
      microservice_name:
        description: 'Name of your service'
        #required: true
        type: string
      RESOURCE_GROUP:
        description: 'Azure Resource Group Name'
        #required: true
        type: string
      aks_cluster_name:
        description: 'AKS Cluster Name'
        type: string
      aks_resource_group:
        description: 'AKS Resource Group'
        type: string
      aks_credentials:
        description: 'AKS Credential'
        type: string
      change_model:
        description: 'Change model sys_id'
        required: true
        type: string
      std_chg_prod_ver:
        description: 'standard change producer version'
        required: true
        type: string
       

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
     
     - name: Set environment variables
       run: |
        echo "AZURE_CLIENT_ID=${{ github.event.inputs.azure_client_id }}" >> $GITHUB_ENV
        echo "AZURE_CLIENT_SECRET=${{ github.event.inputs.azure_client_secret }}" >> $GITHUB_ENV
        echo "AZURE_TENANT_ID=${{ github.event.inputs.azure_tenant_id }}" >> $GITHUB_ENV
        echo "AZURE_SUBSCRIPTION_ID=${{ github.event.inputs.azure_subscription_id }}" >> $GITHUB_ENV
        echo "SERVICENOW_INSTANCE=${{ github.event.inputs.servicenow_instance }}" >> $GITHUB_ENV
        echo "MICROSERVICE_NAME=${{ github.event.inputs.microservice_name }}" >> $GITHUB_ENV
        echo "RESOURCE_GROUP=${{ github.event.inputs.RESOURCE_GROUP }}" >> $GITHUB_ENV
        echo "AKS_CLUSTER_NAME=${{github.event.inputs.aks_cluster_name}}" >> $GITHUB_ENV
        echo "AKS_RESOURCE_GROUP=${{github.event.inputs.aks_resource_group}}" >> $GITHUB_ENV
        echo "AKS_CREDENTIALS=${{github.event.inputs.aks_credentials}}" >> $GITHUB_ENV
    
    # Step 1: Checkout the repository
     - name: Checkout repository
       uses: actions/checkout@v2

    # Step 2: Log in to GitHub Container Registry (ghcr.io)
     - name: Log in to GitHub Container Registry
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

#     - name: Set up Azure CLI
#       uses: azure/login@v1
#       with:
#         creds: >
#          {
#           "clientId": "${{ env.AZURE_CLIENT_ID }}",
#           "clientSecret": "${{ env.AZURE_CLIENT_SECRET }}",
#           "tenantId": "${{ env.AZURE_TENANT_ID }}",
#           "subscriptionId": "${{ env.AZURE_SUBSCRIPTION_ID }}"
#          }

     # Step 3: Extract parent folder name (microservice name)
     - name: Get microservice name (parent folder name)
       id: get_service_name
       run: echo "::set-output name=service_name::$(basename $(pwd))"
     - name: directory content
       run: |
         ls -lart
         ls -lart WeatherForecastApi
     # Step 4: Build the Docker image using the microservice name as tag
     - name: Build Docker image
       run: |
         docker build -t ghcr.io/${{ github.repository_owner }}/${{ steps.get_service_name.outputs.service_name }}:${{ github.sha }} WeatherForecastApi/.
     # Step 5: Push the Docker image to GitHub Packages
     - name: Push Docker image
       run: |
         docker push ghcr.io/${{ github.repository_owner }}/${{ steps.get_service_name.outputs.service_name }}:${{ github.sha }}
 
 ci-management:
   runs-on: ubuntu-latest
   needs: build
   outputs:
    ci_sys_id: ${{steps.discover_ci.outputs.ci_sys_id}}
    
   steps:
     - name: Set environment variables
       run: |
        echo "AZURE_CLIENT_ID=${{ github.event.inputs.azure_client_id }}" >> $GITHUB_ENV
        echo "AZURE_CLIENT_SECRET=${{ github.event.inputs.azure_client_secret }}" >> $GITHUB_ENV
        echo "AZURE_TENANT_ID=${{ github.event.inputs.azure_tenant_id }}" >> $GITHUB_ENV
        echo "AZURE_SUBSCRIPTION_ID=${{ github.event.inputs.azure_subscription_id }}" >> $GITHUB_ENV
        echo "SERVICENOW_INSTANCE=${{ github.event.inputs.servicenow_instance }}" >> $GITHUB_ENV
        echo "MICROSERVICE_NAME=${{ github.event.inputs.microservice_name }}" >> $GITHUB_ENV
        echo "RESOURCE_GROUP=${{ github.event.inputs.RESOURCE_GROUP }}" >> $GITHUB_ENV
        echo "AKS_CLUSTER_NAME=${{github.event.inputs.aks_cluster_name}}" >> $GITHUB_ENV
        echo "AKS_RESOURCE_GROUP=${{github.event.inputs.aks_resource_group}}" >> $GITHUB_ENV
        echo "AKS_CREDENTIALS=${{github.event.inputs.aks_credentials}}" >> $GITHUB_ENV    

     # Extract parent folder name (microservice name)
     - name: Get microservice name (parent folder name)
       id: get_service_name
       run: echo "::set-output name=service_name::$(basename $(pwd))"
       
     # Step 1: Discover or Create Microservice CI in ServiceNow using the service name
     - name: Discover or Create CI for Microservice in ServiceNow
       id: discover_ci
       run: |
         # Define the ServiceNow instance and authentication
         SN_INSTANCE="${{ env.SERVICENOW_INSTANCE }}.service-now.com"
         SN_USER="${{ env.SERVICENOW_USER }}"
         SN_PASS="${{ env.SERVICENOW_PASSWORD }}"
         SERVICE_NAME="${{ steps.get_service_name.outputs.service_name }}"
         # Encode username and password for Basic Auth
         auth_header=$(echo -n "${{ env.SERVICENOW-USER }}:${{ env.SERVICENOW-PASSWORD }}" | base64)
         
         # Discover the CI in ServiceNow
         echo "Attempting to discover CI with name: $SERVICE_NAME"
         ci_response=$(curl -s -X GET \
           "https://$SN_INSTANCE/api/now/table/cmdb_ci?sysparm_query=name=$SERVICE_NAME" \
           --user ${{ secrets.SERVICENOW_USER }}:${{ secrets.SERVICENOW_PASSWORD }} \
           --header "Accept: application/json")
         # Extract sys_id and name if the CI exists
         ci_sys_id=$(echo $ci_response | jq -r '.result[0].sys_id')
         ci_name=$(echo $ci_response | jq -r '.result[0].name')
         
         # Check if CI was found, if not, create it
         if [ -z "$ci_sys_id" ] || [ "$ci_sys_id" == "null" ]; then
           echo "CI not found. Creating a new CI for $SERVICE_NAME..."
           # Create the CI if it doesn't exist
           create_ci_response=$(curl -s -X POST \
             "https://$SN_INSTANCE/api/now/table/cmdb_ci" \
             --user ${{ secrets.SERVICENOW_USER }}:${{ secrets.SERVICENOW_PASSWORD }} \
             --header "Content-Type: application/json" \
             --data '{
               "name": "'"$SERVICE_NAME"'",
               "category": "Application Service",
               "location": "AKS Cluster",
               "app_service_name": "'"$SERVICE_NAME"'"
             }')
           # Extract the sys_id and name of the newly created CI
           ci_sys_id=$(echo $create_ci_response | jq -r '.result.sys_id')
           ci_name=$(echo $create_ci_response | jq -r '.result.name')
           if [ "$ci_sys_id" == "null" ] || [ -z "$ci_sys_id" ]; then
             echo "Error: Failed to create CI for $SERVICE_NAME. Response: $create_ci_response"
             exit 1
           else
             echo "Successfully created CI: $ci_name with sys_id: $ci_sys_id"
           fi
         else
           echo "CI found: $ci_name with sys_id: $ci_sys_id"
         fi
         # Set the output for the discovered or created CI
         echo "ci_sys_id=$ci_sys_id" >> $GITHUB_OUTPUT
         echo "ci_name=$ci_name" >> $GITHUB_OUTPUT
     
     # Step 2: Print CMDB Item Details
     - name: Print CMDB Item
       run: |
        echo "CMDB Item: ${{ steps.discover_ci.outputs.ci_name }} (sys_id: ${{ steps.discover_ci.outputs.ci_sys_id }})"
 
 change-request:
   runs-on: ubuntu-latest
   needs: ci-management
   outputs:
    ci_sys_id: ${{steps.create_change.outputs.change_number}}
   steps:

     - name: Set environment variables
       run: |
        echo "AZURE_CLIENT_ID=${{ github.event.inputs.azure_client_id }}" >> $GITHUB_ENV
        echo "AZURE_CLIENT_SECRET=${{ github.event.inputs.azure_client_secret }}" >> $GITHUB_ENV
        echo "AZURE_TENANT_ID=${{ github.event.inputs.azure_tenant_id }}" >> $GITHUB_ENV
        echo "AZURE_SUBSCRIPTION_ID=${{ github.event.inputs.azure_subscription_id }}" >> $GITHUB_ENV
        echo "SERVICENOW_INSTANCE=${{ github.event.inputs.servicenow_instance }}" >> $GITHUB_ENV
        echo "MICROSERVICE_NAME=${{ github.event.inputs.microservice_name }}" >> $GITHUB_ENV
        echo "RESOURCE_GROUP=${{ github.event.inputs.RESOURCE_GROUP }}" >> $GITHUB_ENV
        echo "AKS_CLUSTER_NAME=${{github.event.inputs.aks_cluster_name}}" >> $GITHUB_ENV
        echo "AKS_RESOURCE_GROUP=${{github.event.inputs.aks_resource_group}}" >> $GITHUB_ENV
        echo "AKS_CREDENTIALS=${{github.event.inputs.aks_credentials}}" >> $GITHUB_ENV
        echo "CHANGE_MODEL=${{github.event.inputs.change_model}}" >> $GITHUB_ENV
        echo "STD_CHG_PROD_VER=${{github.event.inputs.std_chg_prod_ver}}" >> $GITHUB_ENV
        
     # Extract parent folder name (microservice name)
     - name: Get microservice name (parent folder name)
       id: get_service_name
       run: echo "::set-output name=service_name::$(basename $(pwd))"

     # Step 1: Create standard change request based on existing change template for brightlayer.  
     - name: Create Standard Change Request in ServiceNow
       id: create_change
       run: |
         SN_INSTANCE="${{ env.SERVICENOW_INSTANCE }}.service-now.com"
         SERVICE_NAME="${{ steps.get_service_name.outputs.service_name }}"
         CMDB_CI="${{ needs.ci-management.outputs.ci_sys_id }}"
         chg_model_tmp="${{env.CHANGE_MODEL}}"
         std_chg_ver="${{env.STD_CHG_PROD_VER}}"
         
         echo "Creating a change request for $SERVICE_NAME with CI sys_id: $CMDB_CI..."
         # Construct JSON payload with jq
         json_payload=$(jq -n \
           --arg short_description "Deploy $SERVICE_NAME microservice to AKS" \
           --arg description "Standard change for deploying $SERVICE_NAME microservice to AKS using a pre-approved change model." \
           --arg category "Software" \
           --arg type "standard" \
           --arg chg_model "$chg_model_tmp" \
           --arg std_change_producer_version "$std_chg_ver" \
           --arg cmdb_ci "$CMDB_CI" \
           '{
             short_description: $short_description,
             description: $description,
             category: $category,
             type: $type,
             chg_model: $chg_model,
             std_change_producer_version: $std_change_producer_version,
             cmdb_ci: $cmdb_ci
           }')
         # Make the API call
         change_request=$(curl -s -X POST \
           "https://$SN_INSTANCE/api/now/table/change_request" \
           --user ${{ secrets.SERVICENOW_USER }}:${{ secrets.SERVICENOW_PASSWORD }} \
           --header "Content-Type: application/json" \
           --data "$json_payload")
         # Extract and print the change request number for debugging
         change_number=$(echo $change_request | jq -r '.result.number')
         if [ "$change_number" == "null" ] || [ -z "$change_number" ]; then
           echo "Error: Failed to create change request. Response: $change_request"
           exit 1
         else
           echo "Successfully created change request: $change_number"
           echo "change_number=$change_number" >> $GITHUB_OUTPUT
         fi
     
     # Print Change Request Number
     - name: Print Change Request Number
       run: |
        echo "ServiceNow Change Request: ${{ steps.create_change.outputs.change_number }} (sys_id: ${{ steps.create_change.outputs.change_sys_id }})"           
 
 deploy:
   runs-on: ubuntu-latest
   needs: ci-management
   steps:

     - name: Set environment variables
       run: |
        echo "AZURE_CLIENT_ID=${{ github.event.inputs.azure_client_id }}" >> $GITHUB_ENV
        echo "AZURE_CLIENT_SECRET=${{ github.event.inputs.azure_client_secret }}" >> $GITHUB_ENV
        echo "AZURE_TENANT_ID=${{ github.event.inputs.azure_tenant_id }}" >> $GITHUB_ENV
        echo "AZURE_SUBSCRIPTION_ID=${{ github.event.inputs.azure_subscription_id }}" >> $GITHUB_ENV
        echo "SERVICENOW_INSTANCE=${{ github.event.inputs.servicenow_instance }}" >> $GITHUB_ENV
        echo "MICROSERVICE_NAME=${{ github.event.inputs.microservice_name }}" >> $GITHUB_ENV
        echo "RESOURCE_GROUP=${{ github.event.inputs.RESOURCE_GROUP }}" >> $GITHUB_ENV
        echo "AKS_CLUSTER_NAME=${{github.event.inputs.aks_cluster_name}}" >> $GITHUB_ENV
        echo "AKS_RESOURCE_GROUP=${{github.event.inputs.aks_resource_group}}" >> $GITHUB_ENV
        echo "AKS_CREDENTIALS=${{github.event.inputs.aks_credentials}}" >> $GITHUB_ENV    
        
     # Extract parent folder name (microservice name)
     - name: Get microservice name (parent folder name)
       id: get_service_name
       run: echo "::set-output name=service_name::$(basename $(pwd))"
       
     # Step 0: Set AKS context
     #- name: Set AKS context
     #  uses: azure/aks-set-context@v2
     #  with:
     #    resource-group: ${{ env.AKS_RESOURCE_GROUP }}
     #    cluster-name: ${{ env.AKS_CLUSTER_NAME }}
     #    credentials-file: ${{ secrets.AKS_CREDENTIALS }}
     
     # Step 1: Deploy to AKS using Docker image from GitHub Packages
     - name: Deploy to AKS
       id: aks_deployment
       run: |
         # kubectl set image deployment/${{ steps.get_service_name.outputs.service_name }} ${{ steps.get_service_name.outputs.service_name }}= ghcr.io /${{ github.repository_owner }}/${{ steps.get_service_name.outputs.service_name }}:${{ github.sha }}
         # kubectl rollout status deployment/${{ steps.get_service_name.outputs.service_name }}
         echo "deployment successfull"
 
    # Step 2: Rollback step, runs only if deployment fails
     - name: Rollback Deployment
       if: ${{ failure() }}
       run: |
         echo "Deployment failed, executing rollback..."
         # Rollback command (replace with your actual rollback command)
         # kubectl rollout undo -f deployment.yaml  # replace with actual rollback command
          
     # Step 3: Conditionally close the change request if deployment is successful
     - name: Close ServiceNow Change Request
       if: ${{ success() && steps.aks_deployment.conclusion == 'success' }}
       run: |
         change_id=${{ steps.create_change.outputs.change_number }}
         curl -X PATCH \
           "https://${{ env.SERVICENOW_INSTANCE }}.service-now.com/api/now/table/change_request/$change_id" \
           --user ${{ secrets.SERVICENOW_USER }}:${{ secrets.SERVICENOW_PASSWORD }} \
           --header "Content-Type: application/json" \
           --data '{
             "state": "Closed",
             "close_code": "Successful",
             "close_notes": "Deployment of '${{ steps.get_service_name.outputs.service_name }}' to AKS completed successfully"
           }'

     # Step 4: Conditionally close the change request if rollback was executed
     - name: Close Change Request - Rolled Back
       if: ${{ failure() && steps.aks_deployment.conclusion == 'failure' }}
       run: |
         CHANGE_SYS_ID=${{ steps.create_change.outputs.change_number }}
         echo "Closing the change request $CHANGE_SYS_ID as rolled back..."
         # Construct JSON payload for closing the change request as rolled back
         json_payload=$(jq -n \
           --arg state "Closed" \
           --arg close_code "Rolled Back" \
           --arg close_notes "Deployment to AKS failed. Rolled back the changes." \
           '{
             state: $state,
             close_code: $close_code,
             close_notes: $close_notes
           }')
         # Close the change request
         curl -s -X PATCH \
           "https://${{ env.SERVICENOW_INSTANCE }}.service-now.com/api/now/table/change_request/$CHANGE_SYS_ID" \
           --user ${{ secrets.SERVICENOW_USER }}:${{ secrets.SERVICENOW_PASSWORD }} \
           --header "Content-Type: application/json" \
           --data "$json_payload"
